language: node_js

# Travis-CI Caching
cache:
  directories:
    - node_modules
cache:
  apt:true
  directories:
    - node_modules
node_js: stable
install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../
scripts:
  - npm run test
