language: node_js

sudo: false

node_js: stable

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../
  
scripts:
  - npm run test
